service: railway-backend
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    SECURE_CODE: ${env:SECURE_CODE}

functions:
  registerSuperAdmin:
    handler: lambda/authsignUpHandler
    events:
      - http:
          path: api/super-admin/v1/auth/signup
          method: post
          cors: true

  loginSuperAdmin:
    handler: lambda/auth.loginHandler
    events:
      - http:
          path: api/super-admin/v1/auth/login
          method: post
          cors: true

  getAdminsList:
    handler: lambda/lists.getAdminsListHandler
    events:
      - http:
          path: api/super-admin/v1/admins-list
          method: get
          cors: true

  createAdmin:
    handler: lambda/insert.createAdminHandler
    events:
      - http:
          path: api/super-admin/v1/create-admin
          method: post
          cors: true

  getReport:
    handler: lambda/report.getReportHandler
    events:
      - http:
          path: api/super-admin/v1/report-summary
          method: get
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: false
    noPrependStageInUrl: true
